# Global cars dstaset cleaning and preprocessiong

this is the cleaning and preprocessing of the global cars dataset cleaning and preprocessing. Here we have cleaned and preprocessed the dataset by removing missing values, correcting the spellings using regular expressions and removing the outliers from the dataset

## Importing the libraries

In [24]:
# Importing the libraries
import numpy as np # numpy for mathematical calculations
import pandas as pd # pandas for data manipulation
import matplotlib.pyplot as plt # matplotlib for data visulations
import seaborn as sns # seaborn for advanced visualtions

In [25]:
# loading the dataset
df = pd.read_csv("global_car_sales.csv") # here we have used dataset in a csv format

### Visualizing the head of the dataset so that we can see the variance in the data

In [26]:
df.head()

,brand,year,month,country,model,segment,engine_type,price_usd,marketing_spend_usd,dealership_count,fuel_price_usd,gdp_growth_percent,interest_rate_percent,competition_index,units_sold
0,Toyota,2024,10,Spain,Supra,Sedan,Hybrid,34573,474614,20.0,1.66,1.43,3.37,9,1192
1,Tesla,2018,12,Spain,Model 3,Electric,Electric,49727,75488,11.0,1.79,1.13,3.24,7,197
2,Toyota,2015,6,India,Corolla,Sedan,Electric,58338,538524,54.0,0.97,7.40,6.32,4,1800
3,Tesla,2021,1,Germany,Model X,Electric,Electric,119258,50449,5.0,1.94,1.46,2.77,1,NaN
4,Toyota,2016,3,NaN,C-HR,SUV,PETROL,76745,246108,30.0,1.94,1.98,2.81,4,1320

## Making a copy of the dataset

In [27]:
# making a copy of the dataset so that we can compare the two datasets, 
# and the original dataset remains intact
df_copy = df.copy()

In [28]:
df_copy

,brand,year,month,country,model,segment,engine_type,price_usd,marketing_spend_usd,dealership_count,fuel_price_usd,gdp_growth_percent,interest_rate_percent,competition_index,units_sold
0,Toyota,2024,10,Spain,Supra,Sedan,Hybrid,34573,474614,20.0,1.66,1.43,3.37,9,1192
1,Tesla,2018,12,Spain,Model 3,Electric,Electric,49727,75488,11.0,1.79,1.13,3.24,7,197
2,Toyota,2015,6,India,Corolla,Sedan,Electric,58338,538524,54.0,0.97,7.40,6.32,4,1800
3,Tesla,2021,1,Germany,Model X,Electric,Electric,119258,50449,5.0,1.94,1.46,2.77,1,NaN
4,Toyota,2016,3,NaN,C-HR,SUV,PETROL,76745,246108,30.0,1.94,1.98,2.81,4,1320
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8986,Mercedes-Benz,2021,4,China,EQS,Electric,Diesel,70626,263018,43.0,1.03,6.35,3.72,10,653
8987,Volkswagen,2016,11,Germany,Golf,Sedan,Hybrid,24688,218548,88.0,1.97,1.72,2.79,2,1374
8988,Audi,2024,4,Spain,e-tron,Electric,Diesel,74321,482198,26.0,1.73,1.66,3.39,5,897
8989,Audi,2017,5,China,Q7,SUV,Electric,68564,312129,38.0,1.11,5.95,3.69,2,964
8990,Tesla,2016,8,Netherlands,Cybertruck,Electric,Electric,NaN,271947,5.0,1.95,1.69,3.22,8,2112

### checking for nulls in the dataset

In [29]:
df_copy.isnull().sum()

brand                      0
year                       0
month                      0
country                  180
model                      0
segment                  180
engine_type              178
price_usd                273
marketing_spend_usd      270
dealership_count         269
fuel_price_usd           268
gdp_growth_percent       267
interest_rate_percent      0
competition_index          0
units_sold               272
dtype: int64

### checking and removing the duplicates from the dataset

In [30]:
# check for duplicates
df_copy.duplicated().sum()

np.int64(108)

In [31]:
df_copy.drop_duplicates()

,brand,year,month,country,model,segment,engine_type,price_usd,marketing_spend_usd,dealership_count,fuel_price_usd,gdp_growth_percent,interest_rate_percent,competition_index,units_sold
0,Toyota,2024,10,Spain,Supra,Sedan,Hybrid,34573,474614,20.0,1.66,1.43,3.37,9,1192
1,Tesla,2018,12,Spain,Model 3,Electric,Electric,49727,75488,11.0,1.79,1.13,3.24,7,197
2,Toyota,2015,6,India,Corolla,Sedan,Electric,58338,538524,54.0,0.97,7.40,6.32,4,1800
3,Tesla,2021,1,Germany,Model X,Electric,Electric,119258,50449,5.0,1.94,1.46,2.77,1,NaN
4,Toyota,2016,3,NaN,C-HR,SUV,PETROL,76745,246108,30.0,1.94,1.98,2.81,4,1320
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8956,Porsche,2019,11,China,Panamera Sport,Sedan,Hybrid,193397,107322,24.0,1.14,5.88,3.38,9,446
8957,Audi,2017,8,Canada,Q8,SUV,Electric,56952,337819,12.0,NaN,2.03,4.05,1,944
8963,Toyota,2016,9,Brazil,Corolla,Sedan,Electric,62914,288666,16.0,1.27,3.59,10.37,3,1233
8979,Tesla,2020,12,India,Model X Plaid,Electric,Electric,123986,263744,29.0,1.07,6.80,6.50,2,NaN
8987,Volkswagen,2016,11,Germany,Golf,Sedan,Hybrid,24688,218548,88.0,1.97,1.72,2.79,2,1374

In [32]:
#check the mode of the country column
df_copy['country'].mode()

0    UK
Name: country, dtype: str

In [33]:
df_copy['segment'].mode()

0    SUV
Name: segment, dtype: str

In [34]:
df_copy['segment']

0          Sedan
1       Electric
2          Sedan
3       Electric
4            SUV
          ...
8986    Electric
8987       Sedan
8988    Electric
8989         SUV
8990    Electric
Name: segment, Length: 8991, dtype: str

In [35]:
cleanup_map = {
    'electrc': 'electric',
    'petrole': 'petrol',
    'diesal': 'diesel',
    'hybrd': 'hybrid'
}
df_copy['engine_type'] = df_copy['engine_type'].str.lower().str.strip()
df_copy['engine_type'] = df_copy['engine_type'].replace(cleanup_map)

In [36]:
def fill_with_mode(series):
    # Returns the mode if it exists, otherwise the original missing value
    mode = series.mode()
    if not mode.empty:
        return series.fillna(mode.iloc[0])
    return series
df_copy['engine_type'] = df_copy.groupby('model')['engine_type'].transform(fill_with_mode)

In [37]:
df_copy['engine_type'].isna().sum()

np.int64(0)

In [38]:
country_map = {
    # Australia
    'australia': 'Australia',
    'Australlia': 'Australia',
    'AUSTRALIA': 'Australia',
    
    # Brazil
    'Brasil': 'Brazil',
    'BRAZIL': 'Brazil',
    
    # Canada
    'CANADA': 'Canada',
    
    # China
    'CHINA': 'China',
    
    # France
    'Frnce': 'France',
    'FRANCE': 'France',
    
    # Germany
    'GERMANY': 'Germany',
    'Germny': 'Germany',
    'Germnay': 'Germany',
    
    # India
    'INDIA': 'India',
    
    # Italy
    'ITALY': 'Italy',
    
    # Japan
    'JAPAN': 'Japan',
    
    # Mexico
    'MEXICO': 'Mexico',
    
    # Netherlands
    'NETHERLANDS': 'Netherlands',
    
    # Spain
    'SPAIN': 'Spain',
    
    # USA
    'U.S.A': 'USA',
    'US': 'USA',
    'usa': 'USA'
}

df_copy['country'] = df_copy['country'].str.strip()
df_copy['country'] = df_copy['country'].replace(country_map)

In [39]:
segment_map = {
    # SUV
    'S U V': 'SUV',
    'suv': 'SUV',
    'Suv': 'SUV',
    
    # Sedan
    'sedan': 'Sedan',
    'Sedaan': 'Sedan',
    'SEDAN': 'Sedan',
    
    # Electric (Interestingly classified as a segment for some rows)
    'Electrc': 'Electric',
    'electric': 'Electric'
}

# How to apply:
df_copy['segment'] = df_copy['segment'].str.strip()
df_copy['segment'] = df_copy['segment'].replace(segment_map)

In [40]:
# replace the null values in the country column with the mode of the country column
df_copy['country']=df_copy['country'].fillna(df_copy['country'].mode()[0], inplace=True)

In [41]:
df_copy['segment'] = df_copy['segment'].fillna(df['segment'].mode()[0])

In [42]:
df_copy.isna().sum()

brand                      0
year                       0
month                      0
country                    0
model                      0
segment                    0
engine_type                0
price_usd                273
marketing_spend_usd      270
dealership_count         269
fuel_price_usd           268
gdp_growth_percent       267
interest_rate_percent      0
competition_index          0
units_sold               272
dtype: int64

In [43]:
df['model'] = df['model'].str.strip()

In [44]:
df_copy['price_usd'] = df_copy['price_usd'].replace({r'\$': '', r',': ''}, regex=True)
df_copy['price_usd'] = pd.to_numeric(df_copy['price_usd'], errors='coerce')

In [45]:
def fill_with_median(series):
    # Only fill if the group has a valid median
    return series.fillna(series.median())
# Apply the function grouping by 'model'
df_copy['price_usd'] = df_copy.groupby('model')['price_usd'].transform(fill_with_median)
# Fallback: Just in case there's a rare model where ALL prices are missing, 
# fill whatever is left with the median of the entire Brand
df_copy['price_usd'] = df_copy.groupby('brand')['price_usd'].transform(fill_with_median)

In [46]:
# 1. Strip the dollar signs and commas, convert to numeric
df_copy['marketing_spend_usd'] = df_copy['marketing_spend_usd'].replace({r'\$': '', r',': '', r'"': ''}, regex=True)
df_copy['marketing_spend_usd'] = pd.to_numeric(df_copy['marketing_spend_usd'], errors='coerce')

In [47]:
# 2. Fill missing marketing spend with the median of that specific model
df_copy['marketing_spend_usd'] = df_copy.groupby('model')['marketing_spend_usd'].transform(fill_with_median)

In [48]:
# 3. Fallback to Brand median if needed
df_copy['marketing_spend_usd'] = df_copy.groupby('brand')['marketing_spend_usd'].transform(fill_with_median)

In [49]:
df_copy['fuel_price_usd'] = pd.to_numeric(df_copy['fuel_price_usd'], errors='coerce')
df_copy['fuel_price_usd'] = df_copy.groupby(['country', 'year'])['fuel_price_usd'].transform(lambda x: x.fillna(x.median()))
df_copy['gdp_growth_percent'] = pd.to_numeric(df_copy['gdp_growth_percent'], errors='coerce')
df_copy['gdp_growth_percent'] = df_copy.groupby(['country', 'year'])['gdp_growth_percent'].transform(lambda x: x.fillna(x.median()))

In [50]:
df_copy['dealership_count'] = pd.to_numeric(df_copy['dealership_count'], errors='coerce')
df_copy['dealership_count'] = df_copy.groupby(['brand', 'country'])['dealership_count'].transform(lambda x: x.fillna(x.median()))

In [51]:
# 1. Force to numeric
df_copy['units_sold'] = pd.to_numeric(df_copy['units_sold'], errors='coerce')

# 2. Fix negative values by taking the absolute value
df_copy['units_sold'] = df_copy['units_sold'].abs()

# 3. Drop any rows where units_sold is STILL missing
df_copy = df_copy.dropna(subset=['units_sold'])

In [52]:
df_copy = df_copy.drop_duplicates()

In [53]:
df_copy['brand'] = df_copy['brand'].str.strip().str.title()

In [54]:
brand_map = {
    'Bmw': 'BMW',
    'B M W': 'BMW',
    'Audo': 'Audi',
    'Porshe': 'Porsche',
    'Teslla': 'Tesla',
    'Telsla': 'Tesla',
    'Frod': 'Ford',
    'Toyoda': 'Toyota',
    'Toyata': 'Toyota'
}
df_copy['brand'] = df_copy['brand'].replace(brand_map)

In [55]:
df_copy['engine_type'] = df_copy['engine_type'].str.strip().str.lower()

In [56]:
df_copy['year'] = pd.to_numeric(df_copy['year'], errors='coerce')
df_copy.loc[df_copy['year'] > 2025, 'year'] = np.nan

In [57]:
df_copy['month'] = pd.to_numeric(df_copy['month'], errors='coerce')
df_copy.loc[(df_copy['month'] > 12) | (df_copy['month'] < 1), 'month'] = np.nan

In [58]:
df_copy['price_usd'] = pd.to_numeric(df_copy['price_usd'], errors='coerce')
df_copy.loc[df_copy['price_usd'] > 500000, 'price_usd'] = 500000

In [59]:
df_copy = df_copy.dropna(subset=['dealership_count', 'fuel_price_usd', 'gdp_growth_percent'])

In [60]:
df_copy['model'] = df_copy['model'].str.strip()

In [61]:
print("Total rows left:", len(df_copy))
print(df_copy.isna().sum())

Total rows left: 8588
brand                     0
year                     13
month                    19
country                   0
model                     0
segment                   0
engine_type               0
price_usd                 0
marketing_spend_usd       0
dealership_count          0
fuel_price_usd            0
gdp_growth_percent        0
interest_rate_percent     0
competition_index         0
units_sold                0
dtype: int64

In [62]:
df_copy = df_copy.dropna(subset=['year', 'month'])
# Verify it's perfect!
print(df_copy.isna().sum())

brand                    0
year                     0
month                    0
country                  0
model                    0
segment                  0
engine_type              0
price_usd                0
marketing_spend_usd      0
dealership_count         0
fuel_price_usd           0
gdp_growth_percent       0
interest_rate_percent    0
competition_index        0
units_sold               0
dtype: int64

In [63]:
if 'Unnamed: 0' in df_copy.columns:
    df_copy = df_copy.drop(columns=['Unnamed: 0'])

In [64]:
df_copy = df_copy[df_copy['price_usd'] < 500000]

In [65]:
df_copy['dealership_count'] = df_copy['dealership_count'].replace(0, np.nan)
df_copy['dealership_count'] = df_copy.groupby('brand')['dealership_count'].transform(
    lambda x: x.fillna(x.median())
)

In [66]:
df_copy['engine_type'] = df_copy['engine_type'].str.title()

In [67]:
valid_segments = ['Suv', 'Sedan', 'Hatchback', 'Truck', 'Coupe'] # Add any others you have
df_copy['segment'] = df_copy['segment'].str.title().str.strip()

In [68]:
true_segments = (
    df_copy[df_copy['segment'].isin(valid_segments)]
    .groupby('model')['segment']
    .agg(lambda x: pd.Series.mode(x)[0] if not pd.Series.mode(x).empty else np.nan)
)

In [69]:
df_copy['segment'] = df_copy['model'].map(true_segments)
# Just in case mapping left a few NaNs, drop them
df_copy = df_copy.dropna(subset=['segment'])

In [70]:
df_copy.to_csv('cleaned_data.csv')

In [71]:
df_copy.loc[df_copy['engine_type'] == 'Electric', 'segment'] = 'Electric'

In [72]:
df_copy['year'] = df_copy['year'].astype(int)
df_copy['month'] = df_copy['month'].astype(int)

In [73]:
df_copy['units_sold'] = df_copy['units_sold'].astype(int)

In [74]:
print("After:", df_copy.shape)
print("\nColumns:", df_copy.columns.tolist())
print("\nDtypes:\n", df_copy.dtypes)
print("\nMissing values:", df_copy.isnull().sum().sum())
print("Duplicates:", df_copy.duplicated().sum())
print("\nsegment unique:", sorted(df_copy['segment'].unique()))
print("engine_type unique:", sorted(df_copy['engine_type'].unique()))
print("year dtype:", df_copy['year'].dtype, "| sample:", df_copy['year'].unique()[:5])
print("month dtype:", df_copy['month'].dtype)
print("units_sold dtype:", df_copy['units_sold'].dtype)

After: (8236, 15)

Columns: ['brand', 'year', 'month', 'country', 'model', 'segment', 'engine_type', 'price_usd', 'marketing_spend_usd', 'dealership_count', 'fuel_price_usd', 'gdp_growth_percent', 'interest_rate_percent', 'competition_index', 'units_sold']

Dtypes:
 brand                        str
year                       int64
month                      int64
country                      str
model                        str
segment                      str
engine_type                  str
price_usd                float64
marketing_spend_usd      float64
dealership_count         float64
fuel_price_usd           float64
gdp_growth_percent       float64
interest_rate_percent    float64
competition_index          int64
units_sold                 int64
dtype: object

Missing values: 0
Duplicates: 8

segment unique: ['Electric', 'Sedan', 'Suv']
engine_type unique: ['Diesel', 'Electric', 'Hybrid', 'Petrol']
year dtype: int64 | sample: [2024 2018 2015 2016 2022]
month dtype: int64
units_sold dtype: int64

In [75]:
df_copy.to_csv("final_dataset.csv", index=False)

In [76]:
df_copy.drop_duplicates(inplace=True)
df_copy['segment'] = df_copy['segment'].replace('Suv', 'SUV')

In [77]:
df_copy.to_csv("final_dataset.csv", index=False)